version: "3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=dkONLINE1
    - MYSQL_DATABASE=dmji
    - TZ=Asia/Shanghai
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
    - "3306:3306"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./front:/usr/share/nginx/html
    - ./nginx:/etc/nginx/conf.d
    ports:
    - "80:80"
    restart: always

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - redis
    - mysql
    - nginx
    restart: always